### ISSUE TITLE
Practica 1 Reporte de App de Realidad Aumentada

### ISSUE THREAD

**Issue by AdrianGonzalez-17** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AdrianGonzalez-17#2]
[Practica 1 Reporte de App de Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AdrianGonzalez-17/files/8137401/Practica.1.Reporte.de.App.de.Realidad.Aumentada.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
