### ISSUE TITLE
Infografía Realidad Aumentada

### ISSUE THREAD

**Issue by AdrianGonzalez-17** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-AdrianGonzalez-17#3]
![INFOGRAFIA_REALIDAD_AUMENTADA_16620306](https://user-images.githubusercontent.com/77258063/155630270-71b1927f-67d7-461c-86ae-5d772d4206bc.png)

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Calificación..????
